export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_FOOD_SELECTED = 'SET_FOOD_SELECTED';
export const RESET_BUTTONS = 'RESET_BUTTONS';

export const ADD_RESTROOM_CARD = 'ADD_RESTROOM_CARD';
export const ADD_PANNY_TEXT = 'ADD_PANNY_TEXT';
export const ADD_USER_TEXT = 'ADD_USER_TEXT';

export const GET_FLIGHT_INFO_SUCCESS = 'GET_FLIGHT_INFO_SUCCESS';
export const GET_NEXT_FLIGHT_INFO_SUCCESS = 'GET_NEXT_FLIGHT_INFO_SUCCESS';
export const GET_FOOD_ITEMS_SUCCESS = 'GET_FOOD_ITEMS_SUCCESS';
